# Generated by Django 5.1.7 on 2025-05-11 14:58

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chungcu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lockeritem',
            old_name='destination',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='lockeritem',
            name='received_at',
        ),
        migrations.RemoveField(
            model_name='lockeritem',
            name='status',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='feetype',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name_item', models.CharField(max_length=100)),
                ('description_item', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('waiting', 'Chờ nhận'), ('received', 'Đã nhận')], default='waiting', max_length=50)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('locker_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chungcu.lockeritem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
