# Generated by Django 5.1.7 on 2025-04-22 16:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chungcu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residents',
            name='apartments',
        ),
        migrations.AlterUniqueTogether(
            name='apartments',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='apartments',
            name='building',
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=10)),
                ('floor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('area', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chungcu.building')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('identity_card', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], default=0, max_length=2)),
                ('birthday', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('relationship_to_head', models.CharField(choices=[('CH', 'Chủ hộ'), ('VC', 'Vợ/chồng'), ('CT', 'Con cái'), ('KH', 'Khác')], default=1, max_length=2)),
                ('apartment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='chungcu.apartment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('card_number', models.CharField(max_length=10, unique=True)),
                ('license_plate', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('car', 'Ô tô'), ('motorbike', 'Xe máy'), ('bike', 'Xe đạp'), ('Other', 'Khác')], max_length=20)),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chungcu.resident')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LockerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('locker_number', models.CharField(default=1, max_length=10, unique=True)),
                ('destination', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('waiting', 'Chờ nhận'), ('received', 'Đã nhận')], default='waiting', max_length=50)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chungcu.resident')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='household_head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household_head', to='chungcu.resident'),
        ),
        migrations.DeleteModel(
            name='ApartmentResidents',
        ),
        migrations.DeleteModel(
            name='Residents',
        ),
        migrations.DeleteModel(
            name='Apartments',
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('number', 'building')},
        ),
    ]
