# Generated by Django 5.1.7 on 2025-05-11 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chungcu', '0002_rename_destination_lockeritem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='locker_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chungcu.lockeritem'),
        ),
    ]
