# Generated by Django 5.1.7 on 2025-04-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chungcu', '0002_remove_residents_apartments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='identity_card',
            field=models.CharField(max_length=12),
        ),
    ]
