# Generated by Django 5.1.7 on 2025-05-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chungcu', '0004_alter_item_locker_item_alter_lockeritem_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockeritem',
            name='locker_number',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
