# Generated by Django 5.1.7 on 2025-05-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chungcu', '0005_alter_lockeritem_locker_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description_item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
