# Generated by Django 5.1.7 on 2025-05-12 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chungcu', '0006_alter_item_description_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='phone',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='locker_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='chungcu.lockeritem'),
        ),
    ]
