# Generated by Django 5.1.7 on 2025-05-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chungcu', '0007_visitor_phone_alter_item_locker_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingcard',
            name='color',
            field=models.CharField(default='Trắng', max_length=20),
        ),
    ]
