# Generated by Django 5.1.7 on 2025-05-12 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chungcu', '0008_parkingcard_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingcard',
            name='visitor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chungcu.visitor'),
        ),
    ]
