# Generated by Django 5.1.7 on 2025-05-12 07:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chungcu', '0009_alter_parkingcard_visitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='feetype',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='lockeritem',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='parkingcard',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='surveyresponse',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
