# Generated by Django 5.1.7 on 2025-05-12 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chungcu', '0011_remove_complaint_response_complaintresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='chungcu.building'),
        ),
        migrations.AlterField(
            model_name='parkingcard',
            name='visitor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_card', to='chungcu.visitor'),
        ),
    ]
