# Generated by Django 5.1.7 on 2025-05-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chungcu', '0013_remove_survey_active_remove_survey_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
    ]
