# Generated by Django 5.1.7 on 2025-06-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chungcu', '0015_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
