# Generated by Django 5.1.7 on 2025-06-04 15:50

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chungcu', '0016_visitor_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='proof_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('pending', 'Đã thanh toán - chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='chungcu.question'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chungcu.feetype'),
        ),
    ]
