# Generated by Django 5.1.7 on 2025-06-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chungcu', '0017_invoice_proof_image_invoice_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='proof_image',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('pending', 'Đã thanh toán - chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='unpaid', max_length=20),
        ),
    ]
