# Generated by Django 5.1.7 on 2025-06-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chungcu', '0018_remove_invoice_proof_image_remove_invoice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='unpaid', max_length=20),
        ),
    ]
