# Generated by Django 5.1.7 on 2025-06-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chungcu', '0019_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='apartment',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20),
        ),
    ]
