# Generated by Django 5.1.7 on 2025-06-05 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chungcu', '0020_remove_invoice_apartment_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='apartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='chungcu.apartment'),
        ),
    ]
